from . import start
from . import edits
from . import payment
from . import pickup
from . import get_location
from . import information_handler
from . import fikr_bildirish_handler
from . import savat_ortga
from . import biz_bilan_aloqa
from . import product_menu_handler
from . import menus_handlers
from . import product_add_for_admins
from . import product_delete_for_admins
from . import ordering
from . import r_phone
from . import client_comment
from . import picking_payment